import "./globals.css";
import { ReactLenis, useLenis } from 'lenis/react'
import Nav from "./components/Nav/Nav";
import PageTransition from "./components/PageTransition";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <Nav/>
      <ReactLenis root />
        {children}

        <PageTransition />
      </body>
    </html>
  );
}
